version = 1
SPDX-PackageName = "webcomp-mobility-echarging-dashboard"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".env.example", ".pre-commit-config.yaml", "LICENSE.md", ".editorconfig", ".mailmap", ".prettierrc", "CONTRIBUTORS.rst", "**.png", "**.json", "**.ttf"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["(c) NOI Techpark <digital@noi.bz.it>", "(c) 2020 - 2021 STA <info@sta.bz.it>"]
SPDX-License-Identifier = "CC0-1.0"
